name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.17
  flutter_flip_card: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/fonts/
  - assets/images/backend_development.svg
  - assets/images/c-sharp.svg
  - assets/images/dart.svg
  - assets/images/dotnet.svg
  - assets/images/figma.svg
  - assets/images/flutter.svg
  - assets/images/github.svg
  - assets/images/linkedin.svg
  - assets/images/location.svg
  - assets/images/logo.svg
  - assets/images/mail.svg
  - assets/images/me.png
  - assets/images/memoji.png
  - assets/images/phone.svg
  - assets/images/vbnet.svg
  - assets/images/web_development.svg
    
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/Poppins-ThinItalic.ttf
        weight: 100
        style: italic
      - asset: assets/fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Poppins-ExtraLightitalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Lightitalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf # Italic without explicit weight, often defaults to 400
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-Mediumitalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: assets/fonts/Poppins-Black.ttf
        weight: 900
      - asset: assets/fonts/Poppins-BlackItalic.ttf
        weight: 900
        style: italic