name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Build web
        run: flutter build web --release --base-href "/portfolio/"
