name: Web release
on:
  push:
    branches:  [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Create web build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.3"
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get

      - name: Start web release build
        run: flutter build web --release --base-href "/portfolio/"
     
      - name: Upload web build files
        uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: ./build/web

  deploy:
    name: Deploy web build
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download web release
      uses: actions/download-artifact@v4
      with:
        name: web-release

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
